In [456]:
import pandas as pd
import numpy as np

df = pd.read_csv("Dataset.csv")
df.head()

,ApplicantID,Gender,Married,Dependents,Education,SelfEmployed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,A001,Male,Yes,0,Graduate,No,4583,0,128,360,1,Urban,Approved
1,A002,Female,No,1,Not Graduate,Yes,3000,1500,66,360,0,Rural,Rejected
2,A003,Male,Yes,0,Graduate,No,2583,2358,120,360,1,Semiurban,Approved
3,A004,Male,Yes,2,Not Graduate,No,6000,0,141,360,,Urban,Approved
4,A005,Female,Yes,,Graduate,No,5417,4196,267,360,1,Urban,Approved


In [457]:
rows = df.shape[0]
columns = df.shape[1]
print(f"Rows : {rows}\nColumns : {columns}")

Rows : 435
Columns : 13


In [458]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   ApplicantID        435 non-null    object
 1   Gender             435 non-null    object
 2   Married            435 non-null    object
 3   Dependents         321 non-null    object
 4   Education          435 non-null    object
 5   SelfEmployed       283 non-null    object
 6   ApplicantIncome    435 non-null    int64 
 7   CoapplicantIncome  409 non-null    object
 8   LoanAmount         435 non-null    object
 9   Loan_Amount_Term   332 non-null    object
 10  Credit_History     258 non-null    object
 11  Property_Area      435 non-null    object
 12  Loan_Status        435 non-null    object
dtypes: int64(1), object(12)
memory usage: 44.3+ KB


In [459]:
# OBJECT TO INT OR FLOAT :CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History

In [460]:
df.isnull().sum()
df["Loan_Status"] = df["Loan_Status"].map({
    "Approved": 1,
    "Rejected": 0
})

In [461]:
df['Dependents'].unique()

array(['0', '1', '2', ' ', '3+', nan], dtype=object)

In [462]:
df['Dependents'] = df['Dependents'].replace('+3','3')
df['Dependents'] = df['Dependents'].replace(' ', np.nan)
df['Dependents'] = pd.to_numeric(df['Dependents'], errors='coerce')
df['Dependents'] = df['Dependents'].fillna(df["Dependents"].median())
df.head()

,ApplicantID,Gender,Married,Dependents,Education,SelfEmployed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,A001,Male,Yes,0.0,Graduate,No,4583,0,128,360,1,Urban,1
1,A002,Female,No,1.0,Not Graduate,Yes,3000,1500,66,360,0,Rural,0
2,A003,Male,Yes,0.0,Graduate,No,2583,2358,120,360,1,Semiurban,1
3,A004,Male,Yes,2.0,Not Graduate,No,6000,0,141,360,,Urban,1
4,A005,Female,Yes,1.0,Graduate,No,5417,4196,267,360,1,Urban,1


In [463]:
df['Dependents'] = df['Dependents'].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   ApplicantID        435 non-null    object
 1   Gender             435 non-null    object
 2   Married            435 non-null    object
 3   Dependents         435 non-null    int64 
 4   Education          435 non-null    object
 5   SelfEmployed       283 non-null    object
 6   ApplicantIncome    435 non-null    int64 
 7   CoapplicantIncome  409 non-null    object
 8   LoanAmount         435 non-null    object
 9   Loan_Amount_Term   332 non-null    object
 10  Credit_History     258 non-null    object
 11  Property_Area      435 non-null    object
 12  Loan_Status        435 non-null    int64 
dtypes: int64(3), object(10)
memory usage: 44.3+ KB


In [464]:
df["CoapplicantIncome"] = pd.to_numeric(df["CoapplicantIncome"], errors='coerce')
#df["CoapplicantIncome"] = df["CoapplicantIncome"].astype('int64')
df["CoapplicantIncome"] = df["CoapplicantIncome"].fillna(0)
df

,ApplicantID,Gender,Married,Dependents,Education,SelfEmployed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,A001,Male,Yes,0,Graduate,No,4583,0.0,128,360,1,Urban,1
1,A002,Female,No,1,Not Graduate,Yes,3000,1500.0,66,360,0,Rural,0
2,A003,Male,Yes,0,Graduate,No,2583,2358.0,120,360,1,Semiurban,1
3,A004,Male,Yes,2,Not Graduate,No,6000,0.0,141,360,,Urban,1
4,A005,Female,Yes,1,Graduate,No,5417,4196.0,267,360,1,Urban,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,A431,Female,Yes,2,Not Graduate,NaN,10300,0.0,229,360,NaN,Rural,1
431,A432,Male,No,2,Not Graduate,Yes,9475,2639.0,365,300,1,Urban,1
432,A433,Male,Yes,2,Graduate,NaN,2268,0.0,148,240,0,Semiurban,0
433,A434,Male,Yes,1,Not Graduate,No,12555,0.0,64,NaN,1,Urban,1


In [465]:
df["CoapplicantIncome"].unique()

array([    0.,  1500.,  2358.,  4196.,  1516.,  2504., 10968.,   700.,
        8106.,  2840.,  3500.,  2253.,  1040.,  2925.,  1400.,  2033.,
        2669.,  1850.,  2667.,  1305.,  6733.,  6335.,  5963.,  2209.,
         555.,  3286.,  3908.,  6981.,   947.,  2518.,   537.,  6366.,
        3989.,  3894.,  5404.,  3397.,  6574.,  2242.,  2754.,  5808.,
        5357.,  3023.,  7708.,   185.,    44.,  2097.,  1980.,  1927.,
        1330.,  3711.,  3658.,   794.,  6216.,    91.,  1942.,  7368.,
        4076.,    65.,    73.,  5922.,  6032.,  5412.,  1998.,  1595.,
         644.,  1867.,  6588.,  4728.,   204.,   445.,  5918.,  6386.,
        2715.,  1672.,  3230.,  4492.,   275.,  6964.,  7960.,  4716.,
        6047.,  1666.,  3190.,  3724.,  5123.,  7700.,    67.,  4645.,
         849.,  3348.,  2404.,  1035.,  7678.,   885.,  1649.,  2644.,
        3255.,  2223.,  5256.,  1115.,  5569.,  2310.,  2267.,  5151.,
        3538.,   319.,  2997.,  1532.,   821.,   553.,  7992.,  3893.,
      

In [466]:
df["LoanAmount"] = pd.to_numeric(df["LoanAmount"], errors='coerce')
df["LoanAmount"] = df["LoanAmount"].fillna(df["LoanAmount"].median())
df["LoanAmount"] = df["LoanAmount"].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   ApplicantID        435 non-null    object 
 1   Gender             435 non-null    object 
 2   Married            435 non-null    object 
 3   Dependents         435 non-null    int64  
 4   Education          435 non-null    object 
 5   SelfEmployed       283 non-null    object 
 6   ApplicantIncome    435 non-null    int64  
 7   CoapplicantIncome  435 non-null    float64
 8   LoanAmount         435 non-null    int64  
 9   Loan_Amount_Term   332 non-null    object 
 10  Credit_History     258 non-null    object 
 11  Property_Area      435 non-null    object 
 12  Loan_Status        435 non-null    int64  
dtypes: float64(1), int64(4), object(8)
memory usage: 44.3+ KB


In [467]:
df["Credit_History"].unique()

array(['1', '0', ' ', nan], dtype=object)

In [468]:
df["Credit_History"] = pd.to_numeric(df["Credit_History"], errors='coerce')

In [469]:
df["Credit_History"].unique()

array([ 1.,  0., nan])

In [470]:
df["Credit_History"] = df["Credit_History"].fillna(0)
df["Credit_History"] = df["Credit_History"].astype('int64')
df.head()

,ApplicantID,Gender,Married,Dependents,Education,SelfEmployed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,A001,Male,Yes,0,Graduate,No,4583,0.0,128,360,1,Urban,1
1,A002,Female,No,1,Not Graduate,Yes,3000,1500.0,66,360,0,Rural,0
2,A003,Male,Yes,0,Graduate,No,2583,2358.0,120,360,1,Semiurban,1
3,A004,Male,Yes,2,Not Graduate,No,6000,0.0,141,360,0,Urban,1
4,A005,Female,Yes,1,Graduate,No,5417,4196.0,267,360,1,Urban,1


In [471]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   ApplicantID        435 non-null    object 
 1   Gender             435 non-null    object 
 2   Married            435 non-null    object 
 3   Dependents         435 non-null    int64  
 4   Education          435 non-null    object 
 5   SelfEmployed       283 non-null    object 
 6   ApplicantIncome    435 non-null    int64  
 7   CoapplicantIncome  435 non-null    float64
 8   LoanAmount         435 non-null    int64  
 9   Loan_Amount_Term   332 non-null    object 
 10  Credit_History     435 non-null    int64  
 11  Property_Area      435 non-null    object 
 12  Loan_Status        435 non-null    int64  
dtypes: float64(1), int64(5), object(7)
memory usage: 44.3+ KB


In [472]:
df["Loan_Amount_Term"].unique() 

array(['360', ' ', '180', nan, '240', '300'], dtype=object)

In [473]:
df["Loan_Amount_Term"] = pd.to_numeric(df["Loan_Amount_Term"], errors='coerce')
df["Loan_Amount_Term"] = df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].median())
df["Loan_Amount_Term"] = df["Loan_Amount_Term"].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   ApplicantID        435 non-null    object 
 1   Gender             435 non-null    object 
 2   Married            435 non-null    object 
 3   Dependents         435 non-null    int64  
 4   Education          435 non-null    object 
 5   SelfEmployed       283 non-null    object 
 6   ApplicantIncome    435 non-null    int64  
 7   CoapplicantIncome  435 non-null    float64
 8   LoanAmount         435 non-null    int64  
 9   Loan_Amount_Term   435 non-null    int64  
 10  Credit_History     435 non-null    int64  
 11  Property_Area      435 non-null    object 
 12  Loan_Status        435 non-null    int64  
dtypes: float64(1), int64(6), object(6)
memory usage: 44.3+ KB


In [474]:
df["SelfEmployed"].unique()

array(['No', 'Yes', ' ', nan], dtype=object)

In [475]:
df["SelfEmployed"] = df["SelfEmployed"].str.strip()
df["SelfEmployed"] = df["SelfEmployed"].replace('',np.nan)
df["SelfEmployed"] = df["SelfEmployed"].fillna('No')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   ApplicantID        435 non-null    object 
 1   Gender             435 non-null    object 
 2   Married            435 non-null    object 
 3   Dependents         435 non-null    int64  
 4   Education          435 non-null    object 
 5   SelfEmployed       435 non-null    object 
 6   ApplicantIncome    435 non-null    int64  
 7   CoapplicantIncome  435 non-null    float64
 8   LoanAmount         435 non-null    int64  
 9   Loan_Amount_Term   435 non-null    int64  
 10  Credit_History     435 non-null    int64  
 11  Property_Area      435 non-null    object 
 12  Loan_Status        435 non-null    int64  
dtypes: float64(1), int64(6), object(6)
memory usage: 44.3+ KB


In [476]:
#Checking Data if cleaned:

In [477]:
df["Total_Income"] = df["ApplicantIncome"] + df["CoapplicantIncome"]
df["Income_to_Loan_Ratio"] = df["Total_Income"] / (df["LoanAmount"] + 1)
df["Loan_Burden"] = df["LoanAmount"] / (df["Total_Income"] + 1)

for c in df.columns:
    print(f"Column :{c}")
    print(f"{df[c].unique()} \n")

Column :ApplicantID
['A001' 'A002' 'A003' 'A004' 'A005' 'A006' 'A007' 'A008' 'A009' 'A010'
 'A011' 'A012' 'A013' 'A014' 'A015' 'A016' 'A017' 'A018' 'A019' 'A020'
 'A021' 'A022' 'A023' 'A024' 'A025' 'A026' 'A027' 'A028' 'A029' 'A030'
 'A031' 'A032' 'A033' 'A034' 'A035' 'A036' 'A037' 'A038' 'A039' 'A040'
 'A041' 'A042' 'A043' 'A044' 'A045' 'A046' 'A047' 'A048' 'A049' 'A050'
 'A051' 'A052' 'A053' 'A054' 'A055' 'A056' 'A057' 'A058' 'A059' 'A060'
 'A061' 'A062' 'A063' 'A064' 'A065' 'A066' 'A067' 'A068' 'A069' 'A070'
 'A071' 'A072' 'A073' 'A074' 'A075' 'A076' 'A077' 'A078' 'A079' 'A080'
 'A081' 'A082' 'A083' 'A084' 'A085' 'A086' 'A087' 'A088' 'A089' 'A090'
 'A091' 'A092' 'A093' 'A094' 'A095' 'A096' 'A097' 'A098' 'A099' 'A100'
 'A101' 'A102' 'A103' 'A104' 'A105' 'A106' 'A107' 'A108' 'A109' 'A110'
 'A111' 'A112' 'A113' 'A114' 'A115' 'A116' 'A117' 'A118' 'A119' 'A120'
 'A121' 'A122' 'A123' 'A124' 'A125' 'A126' 'A127' 'A128' 'A129' 'A130'
 'A131' 'A132' 'A133' 'A134' 'A135' 'A136' 'A137' 'A138' 

In [478]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
df = df.drop("ApplicantID", axis=1)

In [479]:
X = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]


numcols = X.select_dtypes(include=["int64","float64"]).columns
catcols = X.select_dtypes(include=["object"]).columns

In [480]:
numtr = Pipeline(steps = [
    ("imputer", SimpleImputer(strategy='median')),
    ("Scaler", StandardScaler())
])
cattr = Pipeline(steps = [
    ("imputer", SimpleImputer(strategy='most_frequent')),
    ("encoder1", OneHotEncoder(handle_unknown='ignore'))
])
Preprocessor = ColumnTransformer(
    transformers=[
        ("num",numtr,numcols),
        ("cat",cattr,catcols)
    ])

In [481]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [482]:
model = Pipeline(steps=[
    ("preprocessing", Preprocessor),
    ("classifier", RandomForestClassifier(class_weight="balanced",random_state=42))
])

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [483]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.5632183908045977
              precision    recall  f1-score   support

           0       0.47      0.57      0.51        35
           1       0.66      0.56      0.60        52

    accuracy                           0.56        87
   macro avg       0.56      0.56      0.56        87
weighted avg       0.58      0.56      0.57        87



In [484]:
from xgboost import XGBClassifier
model2 = Pipeline(steps=[
    ('preprocessing', Preprocessor),
    ('classifier', XGBClassifier( n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=42))
])
model2.fit(X_train, y_train)
y2_pred = model2.predict(X_test)

In [485]:
pg = {
    'classifier__n_estimator':[100,300],
    'classifier__max_depth':[3,5,7],
    'classifier__learning_rate':[0.01,1.0],
    'classifier__subsamples':[0.8,1]
}
model2.named_steps['classifier'].feature_importances_

from sklearn.model_selection import cross_val_score

scores = cross_val_score(model2, X, y, cv=5)
print(scores.mean())

0.5103448275862069


In [486]:
# numeric features (unchanged names)
num_features = numcols

# categorical features (from OneHotEncoder)
cat_features = model2.named_steps["preprocessing"] \
    .named_transformers_["cat"] \
    .named_steps["encoder1"] \
    .get_feature_names_out(catcols)

# combine
features = np.concatenate([num_features, cat_features])

# importance from model
importance = model2.named_steps["classifier"].feature_importances_

# dataframe
import pandas as pd

feature_importance_df = pd.DataFrame({
    "Feature": features,
    "Importance": importance
}).sort_values(by="Importance", ascending=False)

feature_importance_df


,Feature,Importance
3,LoanAmount,0.068545
11,Married_No,0.068197
0,Dependents,0.067917
14,Education_Not Graduate,0.057498
2,CoapplicantIncome,0.053990
6,Total_Income,0.053929
1,ApplicantIncome,0.053438
8,Loan_Burden,0.053127
7,Income_to_Loan_Ratio,0.052149
15,SelfEmployed_No,0.049983


In [487]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model2.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.5632183908045977

Classification Report:

              precision    recall  f1-score   support

           0       0.47      0.57      0.51        35
           1       0.66      0.56      0.60        52

    accuracy                           0.56        87
   macro avg       0.56      0.56      0.56        87
weighted avg       0.58      0.56      0.57        87


Confusion Matrix:

[[20 15]
 [23 29]]


In [488]:
scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")
print("\nCV Accuracy Mean:", scores.mean())

# -------------------------
# 13. OPTIONAL: PROBABILITY THRESHOLD TUNING
# -------------------------
probs = model.predict_proba(X_test)[:, 1]
custom_pred = (probs > 0.4).astype(int)

print("\nCustom Threshold Accuracy (0.4):", accuracy_score(y_test, custom_pred))


CV Accuracy Mean: 0.496551724137931

Custom Threshold Accuracy (0.4): 0.6436781609195402


In [489]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [491]:
log_model = Pipeline([
    ("preprocessing", Preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

print("🔵 Logistic Regression Results")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print(classification_report(y_test, y_pred_log))
print(confusion_matrix(y_test, y_pred_log))

🔵 Logistic Regression Results
Accuracy: 0.5517241379310345
              precision    recall  f1-score   support

           0       0.45      0.54      0.49        35
           1       0.64      0.56      0.60        52

    accuracy                           0.55        87
   macro avg       0.55      0.55      0.55        87
weighted avg       0.57      0.55      0.56        87

[[19 16]
 [23 29]]


In [492]:
svm_model = Pipeline([
    ("preprocessing", Preprocessor),
    ("classifier", SVC(kernel="rbf", probability=True))
])

svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

print("🟢 SVM Results")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))

🟢 SVM Results
Accuracy: 0.6206896551724138
              precision    recall  f1-score   support

           0       0.52      0.69      0.59        35
           1       0.73      0.58      0.65        52

    accuracy                           0.62        87
   macro avg       0.63      0.63      0.62        87
weighted avg       0.65      0.62      0.62        87

[[24 11]
 [22 30]]


In [493]:
models = {
    "Logistic Regression": log_model,
    "SVM": svm_model,
    "XGBoost": model
}

for name, m in models.items():
    pred = m.predict(X_test)
    print("\n", name)
    print("Accuracy:", accuracy_score(y_test, pred))


 Logistic Regression
Accuracy: 0.5517241379310345

 SVM
Accuracy: 0.6206896551724138

 XGBoost
Accuracy: 0.5632183908045977


In [494]:
import pandas as pd

def predict_all_models(data_dict):

    # convert dictionary → dataframe
    input_df = pd.DataFrame([data_dict])

    results = {}

    # Logistic Regression
    results["Logistic Regression"] = log_model.predict(input_df)[0]

    # SVM
    results["SVM"] = svm_model.predict(input_df)[0]

    # XGBoost
    results["XGBoost"] = model.predict(input_df)[0]

    return results

new_loan = {
    "Gender": "Male",
    "Married": "Yes",
    "Dependents": 2,
    "Education": "Graduate",
    "SelfEmployed": "No",
    "ApplicantIncome": 6000,
    "CoapplicantIncome": 1500,
    "LoanAmount": 200,
    "Loan_Amount_Term": 360,
    "Credit_History": 1,
    "Property_Area": "Urban",
    "Total_Income": 7500,
    "Income_to_Loan_Ratio": 7500/200,
    "Loan_Burden": 200/7500
}

result = predict_all_models(new_loan)

print("Model Predictions:")
for model_name, pred in result.items():
    status = "Approved" if pred == 1 else "Rejected"
    print(f"{model_name}: {status}")
    
def predict_all_with_proba(data_dict):

    input_df = pd.DataFrame([data_dict])

    results = {}

    results["Logistic Regression"] = log_model.predict_proba(input_df)[0][1]
    results["SVM"] = svm_model.predict_proba(input_df)[0][1]
    results["XGBoost"] = model.predict_proba(input_df)[0][1]

    return results

Model Predictions:
Logistic Regression: Approved
SVM: Approved
XGBoost: Approved
